// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6KPcMHEwc7xYMYyVtAxhS8LTH-_He2I4',
    appId: '1:837708744200:android:e8b06d54b4f3efad6a33bd',
    messagingSenderId: '837708744200',
    projectId: 'redlove-c8037',
    storageBucket: 'redlove-c8037.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBnAg8m7lw6P_pQgJlP0BJVbZieircUhY',
    appId: '1:837708744200:ios:332bdb48282c41596a33bd',
    messagingSenderId: '837708744200',
    projectId: 'redlove-c8037',
    storageBucket: 'redlove-c8037.appspot.com',
    androidClientId: '837708744200-51r4mo4njti2a6ohuilp0g71691e4dtk.apps.googleusercontent.com',
    iosClientId: '837708744200-713ejgsna1teg4vujkffjjhoj4ea9j0u.apps.googleusercontent.com',
    iosBundleId: 'tech.jobayedsumon.redlove',
  );
}
